#!/bin/bash
SRC_DIR=$(realpath "$(dirname ${0})")
ROOT_DIR=$(dirname "${SRC_DIR}")
PREFIX=${1:-/opt/llvm/install}
BLD_DIR=${2:-/opt/llvm/build}
CMPL_JOBS=${3:-$(grep -c -e 'processor\s\+:\s\+[0-9]\+' < /proc/cpuinfo)}
LINK_JOBS=${4:-$(grep MemTotal /proc/meminfo | awk '{printf "%.0f",  $2/(1024*1024*6)}')}
LINKER=lld
mkdir -p "${BLD_DIR}" && \
pushd "${BLD_DIR}" && \
cmake \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=Debug  \
        -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
        -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=${LINKER}" \
        -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=${LINKER}" \
        -DLLVM_ENABLE_PROJECTS="clang" \
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
        -DLLVM_INCLUDE_BENCHMARKS=Off \
        -DLLVM_USE_SPLIT_DWARF=ON \
        -DLLVM_USE_LINKER="${LINKER}" \
        -DLLVM_PARALLEL_COMPILE_JOBS=${CMPL_JOBS} \
        -DLLVM_PARALLEL_LINK_JOBS=${LINK_JOBS} \
        ${ROOT_DIR}/llvm && \
ninja install install-cxx install-cxxabi && \
popd

